Add new docker build script and copy build_ubuntu script in docker di…
aurora-multiphysics/proteus pull request #35
Opened 2024-06-27 16:00 UTC by agwhittle

…rectory.

2024-07-04 08:42 UTC, lukethehuman requested changes
The docker container builds successfully, great work. However, I have left a few comments for changes I'm unsure about. Mainly, either there has been a typo, or we need to make the directory structure more user friendly.

2024-07-04 08:42 UTC, lukethehuman commented on docker/Dockerfile
> -# docker build --rm -t proteus:latest .
Do we want to remove this comment? It looks useful.

2024-07-04 08:42 UTC, lukethehuman commented on docker/Dockerfile
> -    ./run_tests
Is there a reason for removing the tests? Is this to reduce build time?

2024-07-04 08:42 UTC, lukethehuman commented on docker/Dockerfile
> +ENV PROTEUS_DIR=/proteus
The proteus installation is in `/proteus` but the working directory we enter at the end is `/opt/proteus` (see ln 77). This is confusing. The user experience is currently to enter a directory called proteus, run `ls` and be faced with an empty directory. Then the user may find by moving through the directory structure that the actual installation is in another directory called proteus in a different location. Is this a typo and both are meant to be `/opt/proteus`?

2024-07-08 11:01 UTC, agwhittle commented
All issues with Dockerfile should be fixed.

2024-07-08 13:48 UTC, lukethehuman approved these changes
All comments from last review addressed. Branch is ready for merge.

2024-07-08 13:50 UTC, merged